### ISSUE TITLE
Can't change font setting in FLC

### ISSUE THREAD

**Issue by wangbuling** [phenomen/flc#65]
Hello, I am using your FLC client in a Chinese language environment. Recently, for some reason, the font in FLC changed to SimHei (Black Style) instead of the original Microsoft YaHei. I don't know how to modify the font settings in FLC - the SimHei font is quite uncomfortable for me to use. Additionally, reinstalling FLC did not resolve the issue, and I'm currently using the latest version 7.1.5.

![Image](https://github.com/user-attachments/assets/558d6526-7cb1-4b90-9888-59e9ac0ee201)

![Image](https://github.com/user-attachments/assets/37aa17e3-a019-41b9-a370-f86050fe3df0)
I have changed the font setting in Edge but don't work.

**Comment by phenomen** [comment]
I don't think it has anything to do with FLC. It's a default Chromium behavior regarding Chinese fonts (`sans-serif` -> YaHei and `serif` -> SimHei). The best way to change the font would be specifying it in you Chinese core translation module.

Here are variables that Foundry use and that needs to be adjusted in the translation module CSS:
```css
body {
    --font-primary: "Signika", sans-serif;
    --font-sans: "Signika", "Palatino Linotype", sans-serif;
    --font-serif: "Amiri", serif;
    --font-body: var(--font-sans);
    --font-monospace: monospace;
    --font-blockquote: "Signika", "Palatino Linotype", sans-serif;

    --font-h1: "Modesto Condensed", serif;
    --font-h2: "Amiri", serif;
    --font-h3: "Signika", "Palatino Linotype", sans-serif;
    --font-h4: var(--font-h1);
    --font-h5: var(--font-h2);
    --font-h6: var(--font-h3);
}
```
Ask your translation maintainer to fix the issue. Thanks.
